a1 = int(input("Enter Number1 - "))
a2 = int(input("Enter Number2 - "))
a3 = int(input("Enter Number3 - "))
a4 = int(input("Enter Number4 - "))
a5 = int(input("Enter Number5 - "))
a6 = int(input("Enter Number6 - "))
a7 = int(input("Enter Number7 - "))
a8 = int(input("Enter Number8 - "))

s = set()
s.add(a1)
s.add(a2)
s.add(a3)
s.add(a4)
s.add(a5)
s.add(a6)
s.add(a7)
s.add(a8)
print(s)